---
language: php

cache:
  directories:
  - $HOME/.composer/cache/files


before_install:
- |
  function curl_security_check {
    local tmpfile=$(mktemp)  # Create a temporal file in the default temporal folder of the system
    # Lets do some magic for the tmpfile to be removed when this script ends, even if it crashes
    exec {FD_W}>"$tmpfile"  # Create file descriptor for writing, using first number available
    exec {FD_R}<"$tmpfile"  # Create file descriptor for reading, using first number available
    rm "$tmpfile"  # Delete the file, but file descriptors keep available for this script

    ls $1
    curl -H "Accept: text/plain" https://security.sensiolabs.org/check_lock -F lock=@$1 >&$FD_W
    echo $?
    cat <&$FD_R
    echo $?
    grep "No known\* vulnerabilities detected." <&$FD_R
    echo $?
  }


install:
- composer require symfony/form:3.3.12
- |
  install --directory negative
  cd negative
  composer init
  composer require symfony/http-foundation


script:
# This checks that the application doesn't use dependencies with known security vulnerabilities
- curl_security_check composer.lock
- |
  curl -H "Accept: text/plain" https://security.sensiolabs.org/check_lock -F lock=@composer.lock --output composer.txt
  cat composer.txt
  grep --quiet "No known\* vulnerabilities detected." composer.txt

- curl_security_check ../composer.lock
- |
  curl -H "Accept: text/plain" https://security.sensiolabs.org/check_lock -F lock=@../composer.lock --output ../composer.txt
  cat ../composer.txt
  (! grep --quiet "No known\* vulnerabilities detected." ../composer.txt)
  # With a negation to succeed when security vulnerabilities are found.
