---
language: php

cache:
  directories:
  - $HOME/.composer/cache/files


before_install:
- . curl_security_check.sh

install:
- composer require symfony/form:3.3.12
- |
  install --directory negative
  cd negative
  composer init
  composer require symfony/http-foundation


script:
# This checks that the application doesn't use dependencies with known security vulnerabilities
- curl_security_check composer.lock
- (! curl_security_check ../composer.lock)

- dash -c ". curl_security_check.sh ; curl_security_check composer.lock"
- dash -c ". curl_security_check.sh ; (! curl_security_check ../composer.lock)"


after_script:
- |
  curl -H "Accept: text/plain" https://security.sensiolabs.org/check_lock -F lock=@composer.lock --output composer.txt
  cat composer.txt
  grep --quiet "No known\* vulnerabilities detected." composer.txt
  echo $?

- |
  curl -H "Accept: text/plain" https://security.sensiolabs.org/check_lock -F lock=@../composer.lock --output ../composer.txt
  cat ../composer.txt
  (! grep --quiet "No known\* vulnerabilities detected." ../composer.txt)
  # With a negation to succeed when security vulnerabilities are found.
  echo $?
